# Generated by Django 4.2.6 on 2023-11-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'Listings'},
        ),
    ]
